name: 1_setup_ec2

on: 
  workflow_dispatch:

env:
  PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  HOSTNAME: ${{ secrets.HOST_NAME }}
  USER: ${{ secrets.USER }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Upload and run script on EC2
        run: |          
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          
          # Copy the script to the EC2 instance
          echo "Copying script to EC2 instance..."
          scp -o StrictHostKeyChecking=no -i private_key ./00_ec2/ec2_user_data.sh "${USER}@${HOSTNAME}:/home/${USER}/ec2_user_data.sh"
          
          # Verify the file was copied correctly
          echo "Verifying script on EC2 instance..."
          ssh -o StrictHostKeyChecking=no -i private_key "${USER}@${HOSTNAME}" "ls -l /home/${USER}/ec2_user_data.sh"
          
          # SSH into the EC2 instance and run the script
          echo "Running script on EC2 instance..."
          ssh -o StrictHostKeyChecking=no -i private_key "${USER}@${HOSTNAME}" "
            chmod +x /home/${USER}/ec2_user_data.sh &&
            /home/${USER}/ec2_user_data.sh
          "
 
