name: Deploy

on: 
  workflow_dispatch:

env:
  PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  HOSTNAME: ${{ secrets.HOST_NAME }}
  USER: ${{ secrets.USER }}
  
jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Upload and run script on EC2
        run: |

          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          
          # Copy the script to the EC2 instance
          echo "Copying create-cluster script to EC2 instance..."
          scp -o StrictHostKeyChecking=no -i private_key ./01_eksctl/create-cluster.sh "${USER}@${HOSTNAME}:/home/${USER}/create-cluster.sh"
          
          # Verify the file was copied correctly
          echo "Verifying create-cluster script on EC2 instance..."
          ssh -o StrictHostKeyChecking=no -i private_key "${USER}@${HOSTNAME}" "ls -l /home/${USER}/create-cluster.sh"
          
          # SSH into the EC2 instance and run the script
          echo "Running create-cluster script on EC2 instance..."
          ssh -o StrictHostKeyChecking=no -i private_key "${USER}@${HOSTNAME}" "
            chmod +x /home/${USER}/create-cluster.sh &&
            /home/${USER}/create-cluster.sh
          "
 
